# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sergio Leal's Blog
email: sergio [at] sergiolealdev [dot] com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Sergio Leal.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://sergiolealdev.com" # the base hostname & protocol for your site
twitter_username: sergiolealdev
github_username:  sergiolealdev
youtube_username:  sergiolealdev

# Build settings
markdown: kramdown
encoding: utf-8
